---
- name: gather facts
  setup:

# - name: Perform Safe Upgrade
# yum: name='*' state=latest

- name: Copy the NGINX repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: Copy the Elasticsearch repository definition
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/

- name: Copy the Postgresql respository definition
  copy: src=pgdg-10-centos.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for NGINX
  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Create the GPG key for Elasticsearch
  copy: src=GPG-KEY-elasticsearch dest=/etc/pki/rpm-gpg

- name: Create the GPG key for Postgresql
  copy: src=RPM-GPG-KEY-PGDG-10 dest=/etc/pki/rpm-gpg

- include: hostname.yml
- include: swap.yml
  when: swap_enabled is defined and swap_enabled == true
- include: tools.yml
- include: locale.yml
