---
- name: gather facts
  setup:

    # - name: Perform Safe Upgrade
    # yum: name='*' state=latest

- include: hostname.yml
- include: swap.yml
  when: swap_enabled is defined and swap_enabled == true
- include: tools.yml
- include: locale.yml
