- name: Install Tools
  yum: name={{ item }} state=latest update_cache=true
  with_items:
    # Not in this repository:
    # - build-essential
    # - htop
    # - nodejs
    # - wget
    # Consider disabling
    - tmux
    # - vim
    # - git
    # - libcurl-devel

    # - zlib1g-dev
    # - libssl-dev
    # - libreadline-dev
    # - libyaml-dev
    # - libxml2-dev
    # - libxslt1-dev
    # - libffi-dev
    # - libcurl3
    # - libcurl3-gnutls
    # - libcurl4-openssl-dev
