default: &default
  adapter:  postgresql
  pool:     5
  timeout:  5000
  encoding: utf8
  username: {{ deploy_app_name }}
  password: {{ postgresql_app_db_password }}
  host: localhost

production:
  <<: *default
  database: {{ deploy_app_name }}

staging:
  <<: *default
  database: staging_{{ deploy_app_name }}
