---
- name: Download and unpack chruby
  unarchive:
    remote_src: yes
    src: "https://github.com/postmodern/chruby/archive/v{{ chruby_version }}.tar.gz"
    dest: /root/

- name: Install chruby
  make: chdir=/root/chruby-{{ chruby_version }} target=install

- name: Copy chruby.sh
  copy: src=chruby.sh dest=/etc/profile.d/chruby.sh owner=root group=root

- name: Install Bundler
  command: /opt/rubies/ruby-{{ ruby_version }}/bin/gem install bundler
