---
- name: Download and unpack ruby-install
  unarchive:
    remote_src: yes
    src: "https://github.com/postmodern/ruby-install/archive/v{{ ruby_install_version }}.tar.gz"
    dest: /root/

- name: Install ruby-install
  make: chdir=/root/ruby-install-{{ ruby_install_version }} target=install

- name: Create rubies directory
  file: path=/opt/rubies/ state=directory mode=0755 owner=root group=root

- name: Check for rubies
  stat: path=/opt/rubies/ruby-{{ ruby_version }}/
  register: rubies_installed

- name: Install the latest stable Ruby version
  command: /root/ruby-install-{{ ruby_install_version}}/bin/ruby-install ruby {{ ruby_version }}
  when: rubies_installed.stat.isdir is not defined
