---
- name: Install JDK
  yum: name=java-1.8.0-openjdk state=latest

- name: Install Elasticsearch
  yum: name=elasticsearch state=latest

- name: Ensure Elasticsearch service is up
  action: service name=elasticsearch state=started enabled=yes
