---
- name: Install Nginx
  yum: name=nginx state=latest

- name: Check for dhparam.pem
  stat: path=/etc/nginx/dhparam.pem
  register: dhparam

- name: Generate dhparam
  command: openssl dhparam -out /etc/nginx/dhparam.pem 2048
  when: nginx_https_enabled is defined and nginx_https_enabled == true and dhparam.stat.exists == false

- name: Copy nginx configuration (with HTTPS enabled)
  template: src=nginx_app_config_https dest=/etc/nginx/conf.d/{{ deploy_app_name }}.conf owner=root group=root
  when: nginx_https_enabled is defined and nginx_https_enabled == true

- name: Copy nginx configuration (without HTTPS enabled)
  template: src=nginx_app_config dest=/etc/nginx/conf.d/{{ deploy_app_name }}.conf owner=root group=root
  when: nginx_https_enabled is defined and nginx_https_enabled != true

- name: Disable default config
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Move SELinux policy file
  copy:
    src: nginx.te
    dest: /home/{{ deploy_user }}/nginx.te

- name: Begin compiling SELinux policy file
  command: checkmodule -M -m -o nginx.mod nginx.te

- name: Finish compiling SELinux policy file
  command: semodule_package -o nginx.pp -m nginx.mod

- name: Install SELinux policy file
  command: semodule -i nginx.pp
