---
- name: Install Postgresql
  yum: name={{ item }} state=latest update_cache=true
  with_items:
    - postgresql-server
    - postgresql-contrib
    - postgresql-devel # For libpq-fe.h
    - python-psycopg2

- name: Ensure data directory is empty
  file:
    path: /var/lib/pgsql/data
    state: absent

- name: Initialize cluster
  command: postgresql-setup initdb

- name: Ensure Postgresql service is up
  service: name=postgresql state=started enabled=yes

- name: Restart Postgresql service
  service: name=postgresql state=restarted

- name: Create Postgresql User
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ deploy_app_name }}"
    state: present
    role_attr_flags: NOCREATEDB,NOSUPERUSER
    password: "{{ postgresql_app_db_password }}"

- name: Create Production Postgresql Database
  postgresql_db:
    name: "{{ deploy_app_name }}"
    state: present
    encoding: UTF-8
  when: staging == false
  become: true
  become_user: postgres

- name: Create Staging Postgresql Database
  postgresql_db:
    name: "staging_{{ deploy_app_name }}"
    state: present
    encoding: UTF-8
  when: staging == true
  become: true
  become_user: postgres

- name: Give user access to database
  postgresql_user:
    name: "{{ deploy_app_name }}"
    db: "{{ deploy_app_name }}"
    priv: ALL
  become: true
  become_user: postgres

- name: Ensure no one else can access the database
  postgresql_privs:
    db: "{{ deploy_app_name }}"
    role: PUBLIC
    type: database
    priv: ALL
    state: absent
  become: true
  become_user: postgres
