---
- name: Install Postgresql
  yum: name={{ item }} state=latest update_cache=true
  with_items:
    - postgresql-server
    - postgresql-contrib

- name: Create Postgresql Database
  postgresql_db: name={{ deploy_app_name }}
            state=present
            encoding=utf8mb4

- name: Ensure Postgresql service is up
  service: name=postgresql state=started enabled=yes

- name: copy .my.cnf file with root password credentials
  template:
    src=templates/my.cnf
    dest=/root/.my.cnf
    owner=root
    mode=0600

- name: Update Postgresql root password for all root accounts
  postgresql_user: name=root
              host={{ item }}
              password={{ postgresql_root_db_password }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Ensure anonymous users are not in the database
  postgresql_user: name='' host={{ item }} state=absent
  with_items:
    - $inventory_hostname
    - $ansible_hostname
    - localhost

- name: Create Postgresql User
  postgresql_user: name={{ deploy_app_name }}
              priv={{ deploy_app_name }}.*:ALL
              state=present
              password="{{ postgresql_app_db_password }}"
